JvMTECH:
  NeosHardening:
    passwordRequirements:
      minLength: 12
      upperAndLowerCase: true
      numbers: true
      specialChars: true
      maxConsecutiveLetters: 8
      maxConsecutiveNumbers: 5

    checkPasswordHistory: false
    passwordHistoryLength: 10
